<?php


namespace App\Modules\Client\Facades;


use App\Facades\ModuleFacade;
use App\Models\Client;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\Log;

class ClientsFacade extends ModuleFacade
{
    protected function model(): string
    {
        return Client::class;
    }

    /**
     * @return mixed
     */
    public function getInternals()
    {
        return $this->model->internal()->get();
    }

    /**
     * @return mixed
     */
    public function getExternals()
    {
        return $this->model->external()->get();
    }

    /**
     * @param string $deleted
     * @return mixed
     */
    public function clients(string $deleted = '')
    {
        return ($deleted) ? $this->onlyTrashed() : $this->model::query();
    }

    /**
     * @param $data
     * @return mixed
     */
    public function create($data)
    {
        try {
            $this->authorize('create', Client::class);
        } catch (AuthorizationException $e) {
            Log::error(auth()->user()->email. ' tried to create the client');
        }
        return $this->model->create($data);
    }

    /**
     * @param $data
     * @param int $id
     * @return mixed
     */
    public function update($data, int $id)
    {
        try {
            $this->authorize('update', Client::class);
        } catch (AuthorizationException $e) {
            Log::error(auth()->user()->email. ' tried to update the client with id: ' . $id);
        }
        return $this->findOrFail($id)->update($data);
    }

    /**
     * @param array|int $ids
     * @return mixed
     */
    public function delete($ids)
    {
        try {
            $this->authorize('delete', Client::class);
        } catch (AuthorizationException $e) {
            Log::error(auth()->user()->email. ' tried to delete the client with id: ' . $ids);
        }
        return parent::delete($ids); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     */
    public function restore(int $id)
    {
        $client = $this->onlyTrashed()->findOrFail($id);
        try {
            $this->authorize('restore', $client);
        } catch (AuthorizationException $e) {
            Log::error(auth()->user()->email. ' tried to restore the client with id: ' . $id);
        }
        $client->restore();
        $client->save();
    }

    /**
     * @return mixed
     */
    public function onlyTrashed()
    {
        return $this->model->onlyTrashed();
    }
}
